linkedinConfig:
APIKey: kgaqqwflejmf
secretKey: EiekpaNtuGYuD49B
oAuthUserToken: bec92e2f-b9c5-4a17-9305-87949edf42c8
oAuthUserSecret: abe041a5-84f9-4a87-99aa-9171c99fbd45
oAuthSampleAccessKey: AQSW4Aw1d7X7zm-v69j1YFxRkcf1cfAHumDZx69aoBKdOTU0eKOQyDQXthm5DtYJcjU6u5Uq5vzwxGQHfocAVvHn_ZYUfRrew-zDkai-GJ2TxMAlVL4

AQTFDY3P2k3mkE7u9zV_fwLIYilGWjTSFVsY0PDy9Jkai-bfOPQbEIGvSFhXfne0L1_xDxcql9k9A4kVqQK8xm1J4ZZTzCrzP5oXgdaLNwcyJtgvEcY