http:
  port: 8088
  adminPort: 8089

logging:
  console:
    enabled: true
    threshold: DEBUG

  file:
    enabled: true
    threshold: ALL
    filenamePattern: /var/log/terapeakservice.log
    maxFileSize: 50MB
    retainedFileCount: 5

  loggers:
    "com.terapeak.platform": DEBUG

linkedInConfig:
  apiKey: kgaqqwflejmf
  secretKey: EiekpaNtuGYuD49B
  oAuthUserToken: bec92e2f-b9c5-4a17-9305-87949edf42c8
  oAuthUserSecret: abe041a5-84f9-4a87-99aa-9171c99fbd45
  oAuthSampleAccessKey: AQSW4Aw1d7X7zm-v69j1YFxRkcf1cfAHumDZx69aoBKdOTU0eKOQyDQXthm5DtYJcjU6u5Uq5vzwxGQHfocAVvHn_ZYUfRrew-zDkai-GJ2TxMAlVL4
